spring:
  # 数据源配置
  datasource:
    # 主数据源配置
    primary:
      # 连接池配置
      type: com.alibaba.druid.pool.DruidDataSource
      # 初始化大小
      initialSize: 10
      # 最小空闲数
      minIdle: 10
      # 最大活动数
      maxActive: 50
      # 连接等待超时时间
      maxWait: 60000
      # 隔多久进行一次检测(检测可以关闭的空闲连接)
      timeBetweenEvictionRunsMillis: 60000
      # 连接在池中的最小生存时间
      minEvictableIdleTimeMillis: 300000
      # 验证查询
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 是否打开PSCache
      poolPreparedStatements: true
      # 每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall #,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # druid监控视图配置
      # 视图请求路径
      druidUrl: /druid/*
      # 允许访问ip（多个ip用逗号间隔）
      allowIp: 127.0.0.1
      # 拒绝访问ip (与allow存在共同时，deny优先于allow）
      denyIp: 127.0.0.1
      # 视图登录用户名
      loginUsername: admin
      # 视图登录密码
      loginPassword: admin
      # 是否能够重置数据
      resetEnable: true
      # druid切面拦截器匹配（多个包用;间隔）
      druidStatPointcutPatterns: com.kamingpan.infrastructure.*.service.*;com.kamingpan.infrastructure.*.mapper.*;
