javamelody:
  # Enable JavaMelody auto-configuration (optional, default: true)
  enabled: true

  # Data source names to exclude from monitoring (optional, comma-separated)
  excluded-datasources: secretSource,topSecretSource

  # Enable monitoring of Spring services and controllers (optional, default: true)
  # management-endpoint-monitoring-enabled: false

  # Initialization parameters for JavaMelody (optional)
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # log http requests:
    # log: true

    # to exclude images, css, fonts and js urls from the monitoring:
    # url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)

    # to aggregate digits in http requests:
    # http-transform-pattern: \d+

    # to add basic auth:
    authorized-users: admin:admin

    # to add white ip list:
    # allowed-addr-pattern: 127.0.0.1

    # to change the default storage directory:
    # storage-directory: /usr/local/logs/infrastructure/management/javamelody

    # to change the default "/monitoring" path:
    # monitoring-path: /monitoring

    # to allow frame(DENY, SAMEORIGIN, ALLOW-FROM)
    x-frame-options: SAMEORIGIN
