spring:
  redis:
    # 服务器地址
    host: 127.0.0.1
    # 服务器连接端口
    port: 6379
    # 密码
    # password: password
    # 数据库索引
    database: 0
    # 连接超时时间（单位：毫秒）
    timeout: 500
    # 是否开启事务管理控制
    # enable-transaction-support: false

    jedis:
      # 连接池配置
      pool:
        # 最大连接数
        max-active: 30
        # 最大阻塞等待时间
        max-wait: -1
        # 最大空闲连接
        max-idle: 10
        # 最小空闲连接
        min-idle: 0
