# 小程序配置
mini-program:
  # 小程序appID(应用ID)
  app-id: APP_ID
  # 小程序appSecret(应用密钥)
  app-secret: SECRET
  # 小程序开发者模式配置token(令牌)
  token: TOKEN
  # 小程序开发者模式配置aesKey(消息加解密密钥)
  aes-key: AES_KEY

  # 缓存类型（用于缓存微信access_token等，目前支持local和redis两种，local只支持单机部署）
  cache-type: redis
